name: CICD

on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout Source
        uses: actions/checkout@v3 
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
      - run: sudo docker build -t nodetest .
      - run: |
          CONTAINER_NAME=nodejs
          sudo docker stop $CONTAINER_NAME || true
          sudo docker run -d -p 5000:5000 --name $CONTAINER_NAME nodetest